import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FadeContent from "./components/FadeContent";
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portfolio - Ayush",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  minimumScale: 1,
  userScalable: true,
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body
        className={`${inter.variable} antialiased font-sans`}
      >
          <FadeContent blur={true} duration={1000} easing="ease-out" initialOpacity={0}>
            {/* Anything placed inside this container will be fade into view */}
            {children}
            <SpeedInsights />
          </FadeContent>
      </body>
    </html>
  );
}
