import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FadeContent from "./components/FadeContent";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Portfolio - Ayush",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased font-sans`}
      >
          <FadeContent blur={true} duration={1000} easing="ease-out" initialOpacity={0}>
            {/* Anything placed inside this container will be fade into view */}
            {children}
          </FadeContent>
      </body>
    </html>
  );
}
